package core.math.Core;

public enum SolverStatus {
    SUCCESS,

    INVALID_INITIAL_BRACKET,
    INVALID_INITIAL_GUESS,

    NAN_EXPLOSION,
    FAILED_TO_GENERATE_HISTORICAL_POINTS,
    DUPLICATE_Y_VALUES,
    MAX_ITERATIONS_EXCEEDED,
    POSSIBLE_ASYMPTOTE_REACHED,
    FAILED_TO_GENERATE_POSSIBLE_INTERVAL
}
