package math;

public enum ODEStatus {
    SUCCESS,
    IN_PROGRESS,
    INTERRUPTED,

    POSSIBLE_ASYMPTOTE,
    ENCOUNTERED_NAN,
    INVALID_ARGUMENTS,
    EXCEEDED_MAX_ITERATIONS,
    STEPSIZE_UNDERFLOW,
    INVALID_STEPSIZE
}
